### ISSUE TITLE
Create demo application and deploy to managed cloud provider's Kubernetes

### ISSUE THREAD

**Issue by crushten** [crushten/go_endpoint_cloud#1]
>Build an application in the programming language of your choice that exposes a REST endpoint
that returns the following JSON payload with the current timestamp and a static message:
```json
{
 “message”: “Automate all the things!”,
 “timestamp”: 1529729125
}
```
>The application must be deployed on a Kubernetes cluster running in a public cloud provider of
your choice. The provisioning of the cluster as well as the deployment of the application must be
done through code.

Tasks:
- [x]  Create application that exposes REST endpoint and return JSON #2
- [x]  Use Terraform to provision k8s cluster and related services #3
- [x]  Deploy application to k8s cluster #11 
- [x] #7
- [x] Provide a single command to launch the environment and deploy the application.
    * Some prerequisites are OK as long as they are properly documented.
- [ ]  We should be able to deploy and run the application in our own public cloud accounts.
- [ ]  Include some form of automated tests to validate the environment. #13

**Comment by crushten** [comment]
gin needs to be in "release" mode so might need variable to handle that somewhere. Perhaps in the docker container but also maybe locally. So if `go run .` keep it in debug but if `go build .` then release mode maybe.

**Comment by crushten** [comment]
## Overview

* Application with API
* Cloud (AWS)
* Managed Kubernetes (EKS)
* Deployment

### Tools/Languages
* AWS CLI
* Docker
* Git
* Go
* Terraform

### Problems
* [Timestamp](https://github.com/crushten/go_endpoint_cloud/blob/main/terraform/application/main.go#L18)
* [Docker](https://github.com/crushten/go_endpoint_cloud/blob/main/terraform/docker_repo.tf#L15)
* [Deployment](https://github.com/crushten/go_endpoint_cloud/blob/main/terraform/kubernetes.tf#L8)

### Improvements
* Time
* Questions

### Takeaways/Learnings
* Policies
* Cloud
* Terraform

### Todo
* Pipelines
* Local Dev
* Metrics/Log

### Questions
* Terraform IAM

**Comment by crushten** [comment]
## Overview

* Application with API
* Cloud (AWS)
* Managed Kubernetes (EKS)
* Deployment

### Tools/Languages
* AWS CLI
* Docker
* Git
* Go
* Terraform

### Problems
* [Timestamp](https://github.com/crushten/go_endpoint_cloud/blob/main/application/main.go#L18)
* [Docker](https://github.com/crushten/go_endpoint_cloud/blob/main/terraform/docker_repo.tf#L15)
* [Deployment](https://github.com/crushten/go_endpoint_cloud/blob/main/terraform/kubernetes.tf#L8)

### Improvements
* Time
* Questions
* Patience

### Takeaways/Learnings
* Policies
* Cloud
* Terraform

### Todo
* Pipelines
* Local Dev
* Metrics/Log
* TLS

### Questions
* Terraform IAM
* Feedback

**Comment by crushten** [comment]
No idea if anyone looked at the code but probably doesnt matter. The healthcheck thing also is fine. Will close this ticket now.
