### ISSUE TITLE
Add APM, logging, and general metrics to the application and Infrastructure

### ISSUE THREAD

**Issue by crushten** [crushten/go_endpoint_cloud#20]
Would be nice to get some insights and monitoring for the Infrastructure and application. CloudTrail has some stuff in it but CloudWatch isnt setup. Not sure to what extent CloudTrail is setup. 

- [ ] Add APM to application
- [ ] Ensure application logs are sent to CloudTrail/CloudWatch
- [ ] Ensure EKS is logging to CloudTrail/CloudWatch
- [ ] Ensure K8S is logging to CloudTrail/CloudWatch
- [ ] Ensure Containers have monitoring and logging enabled

**Comment by crushten** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log

https://docs.bridgecrew.io/docs/logging_9-enable-vpc-flow-logging

https://github.com/crushten/go_endpoint_cloud/blob/main/terraform/vpc.tf#L28

Might be good to set that up as well.
