### ISSUE TITLE
Create terraform scripts to provision Kubernetes cluster and deploy application

### ISSUE THREAD

**Issue by crushten** [crushten/go_endpoint_cloud#3]
Terraform was chosen to provision and deploy the cluster/application since it is popular. It has a lot of modules/provisions/documentation around provisioning to the different cloud providers.

AWS will be the chosen cloud provider since it is also popular and has a lot of support and documentation for it.

Tasks:
- [x] Create Terraform directory to hold scripts [related issue](#6)
- [x] Create Terraform provisioning for EKS
     - [x]  VPC
     - [x]  Security Groups
     - [x]  The Cluster itself
- [ ] #9
- [x] #10
- [x] #11
- [ ] #13

**Comment by crushten** [comment]
Deployments are now done. Not sure about the healthcheck stuff though.

**Comment by crushten** [comment]
The remote support will be needed for the pipelines.

**Comment by crushten** [comment]
The state for Terraform is more helpful for the pipelines. Also the healthcheck has been added already so will close this ticket. The other linked tickets can be worked on but are no longer needed for this meta.
