### ISSUE TITLE
Setup AWS account, policies, roles, users. billing. etc

### ISSUE THREAD

**Issue by crushten** [crushten/go_endpoint_cloud#4]
Since AWS is the chosen cloud provider will need to setup everything.

Tasks:
- [x] Create non root user to manage AWS account
- [x]  Create users for services
     - [x]  Terraform
     - [x]  Github Actions
- [x] Add proper policies for management account
- [x]  Add proper policies for service accounts #5 
- [x] #8

**Comment by crushten** [comment]
Everything now should its initial permissions will just need to monitor and see what else should be adjusted.

**Comment by crushten** [comment]
Budget and alert has been set. Will have to see how that goes.
