### ISSUE TITLE
Create README to document all the things

### ISSUE THREAD

**Issue by crushten** [crushten/go_endpoint_cloud#7]
Need to document the steps to run, build, test, and deploy the application and cluster.

Tasks:
- [x] Document the application #2
    - [x]  Document how to build the app
    - [x]  Document how to run the app
    - [x]  Document how to test the app
    - [x]  Document how to deploy the app
- [x] #12
    - [x]  Document how to provision the cluster
    - [x]  Document how to test/verify the cluster

**Comment by crushten** [comment]
Sigh forgot to add `curl` to the application docs. Need to do that for testing locally.

**Comment by crushten** [comment]
If move the app dir does indeed work then ithe docs need to be updated.

**Comment by crushten** [comment]
This can be closed now as well.
